// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/rates/v1/rates.proto

package ratesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculationMethod int32

const (
	CalculationMethod_CALCULATION_METHOD_UNSPECIFIED CalculationMethod = 0
	CalculationMethod_CALCULATION_METHOD_TOP_N       CalculationMethod = 1
	CalculationMethod_CALCULATION_METHOD_AVG_N_M     CalculationMethod = 2
)

// Enum value maps for CalculationMethod.
var (
	CalculationMethod_name = map[int32]string{
		0: "CALCULATION_METHOD_UNSPECIFIED",
		1: "CALCULATION_METHOD_TOP_N",
		2: "CALCULATION_METHOD_AVG_N_M",
	}
	CalculationMethod_value = map[string]int32{
		"CALCULATION_METHOD_UNSPECIFIED": 0,
		"CALCULATION_METHOD_TOP_N":       1,
		"CALCULATION_METHOD_AVG_N_M":     2,
	}
)

func (x CalculationMethod) Enum() *CalculationMethod {
	p := new(CalculationMethod)
	*p = x
	return p
}

func (x CalculationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalculationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_rates_v1_rates_proto_enumTypes[0].Descriptor()
}

func (CalculationMethod) Type() protoreflect.EnumType {
	return &file_api_proto_rates_v1_rates_proto_enumTypes[0]
}

func (x CalculationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalculationMethod.Descriptor instead.
func (CalculationMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rates_v1_rates_proto_rawDescGZIP(), []int{0}
}

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        CalculationMethod      `protobuf:"varint,1,opt,name=method,proto3,enum=rates.v1.CalculationMethod" json:"method,omitempty"`
	N             uint32                 `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	M             uint32                 `protobuf:"varint,3,opt,name=m,proto3" json:"m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_api_proto_rates_v1_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rates_v1_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rates_v1_rates_proto_rawDescGZIP(), []int{0}
}

func (x *GetRatesRequest) GetMethod() CalculationMethod {
	if x != nil {
		return x.Method
	}
	return CalculationMethod_CALCULATION_METHOD_UNSPECIFIED
}

func (x *GetRatesRequest) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *GetRatesRequest) GetM() uint32 {
	if x != nil {
		return x.M
	}
	return 0
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           float64                `protobuf:"fixed64,1,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid           float64                `protobuf:"fixed64,2,opt,name=bid,proto3" json:"bid,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_api_proto_rates_v1_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rates_v1_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rates_v1_rates_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesResponse) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *GetRatesResponse) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *GetRatesResponse) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_api_proto_rates_v1_rates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rates_v1_rates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rates_v1_rates_proto_rawDescGZIP(), []int{2}
}

type HealthcheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_api_proto_rates_v1_rates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rates_v1_rates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rates_v1_rates_proto_rawDescGZIP(), []int{3}
}

func (x *HealthcheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthcheckResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

var File_api_proto_rates_v1_rates_proto protoreflect.FileDescriptor

const file_api_proto_rates_v1_rates_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/rates/v1/rates.proto\x12\brates.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x0fGetRatesRequest\x123\n" +
	"\x06method\x18\x01 \x01(\x0e2\x1b.rates.v1.CalculationMethodR\x06method\x12\f\n" +
	"\x01n\x18\x02 \x01(\rR\x01n\x12\f\n" +
	"\x01m\x18\x03 \x01(\rR\x01m\"s\n" +
	"\x10GetRatesResponse\x12\x10\n" +
	"\x03ask\x18\x01 \x01(\x01R\x03ask\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\x01R\x03bid\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\"\x14\n" +
	"\x12HealthcheckRequest\"h\n" +
	"\x13HealthcheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x129\n" +
	"\n" +
	"checked_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt*u\n" +
	"\x11CalculationMethod\x12\"\n" +
	"\x1eCALCULATION_METHOD_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CALCULATION_METHOD_TOP_N\x10\x01\x12\x1e\n" +
	"\x1aCALCULATION_METHOD_AVG_N_M\x10\x022\x9d\x01\n" +
	"\fRatesService\x12A\n" +
	"\bGetRates\x12\x19.rates.v1.GetRatesRequest\x1a\x1a.rates.v1.GetRatesResponse\x12J\n" +
	"\vHealthcheck\x12\x1c.rates.v1.HealthcheckRequest\x1a\x1d.rates.v1.HealthcheckResponseB<Z:github.com/LaboroOptimus/grinex/api/proto/rates/v1;ratesv1b\x06proto3"

var (
	file_api_proto_rates_v1_rates_proto_rawDescOnce sync.Once
	file_api_proto_rates_v1_rates_proto_rawDescData []byte
)

func file_api_proto_rates_v1_rates_proto_rawDescGZIP() []byte {
	file_api_proto_rates_v1_rates_proto_rawDescOnce.Do(func() {
		file_api_proto_rates_v1_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rates_v1_rates_proto_rawDesc), len(file_api_proto_rates_v1_rates_proto_rawDesc)))
	})
	return file_api_proto_rates_v1_rates_proto_rawDescData
}

var file_api_proto_rates_v1_rates_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_rates_v1_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_rates_v1_rates_proto_goTypes = []any{
	(CalculationMethod)(0),        // 0: rates.v1.CalculationMethod
	(*GetRatesRequest)(nil),       // 1: rates.v1.GetRatesRequest
	(*GetRatesResponse)(nil),      // 2: rates.v1.GetRatesResponse
	(*HealthcheckRequest)(nil),    // 3: rates.v1.HealthcheckRequest
	(*HealthcheckResponse)(nil),   // 4: rates.v1.HealthcheckResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_proto_rates_v1_rates_proto_depIdxs = []int32{
	0, // 0: rates.v1.GetRatesRequest.method:type_name -> rates.v1.CalculationMethod
	5, // 1: rates.v1.GetRatesResponse.received_at:type_name -> google.protobuf.Timestamp
	5, // 2: rates.v1.HealthcheckResponse.checked_at:type_name -> google.protobuf.Timestamp
	1, // 3: rates.v1.RatesService.GetRates:input_type -> rates.v1.GetRatesRequest
	3, // 4: rates.v1.RatesService.Healthcheck:input_type -> rates.v1.HealthcheckRequest
	2, // 5: rates.v1.RatesService.GetRates:output_type -> rates.v1.GetRatesResponse
	4, // 6: rates.v1.RatesService.Healthcheck:output_type -> rates.v1.HealthcheckResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_rates_v1_rates_proto_init() }
func file_api_proto_rates_v1_rates_proto_init() {
	if File_api_proto_rates_v1_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rates_v1_rates_proto_rawDesc), len(file_api_proto_rates_v1_rates_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rates_v1_rates_proto_goTypes,
		DependencyIndexes: file_api_proto_rates_v1_rates_proto_depIdxs,
		EnumInfos:         file_api_proto_rates_v1_rates_proto_enumTypes,
		MessageInfos:      file_api_proto_rates_v1_rates_proto_msgTypes,
	}.Build()
	File_api_proto_rates_v1_rates_proto = out.File
	file_api_proto_rates_v1_rates_proto_goTypes = nil
	file_api_proto_rates_v1_rates_proto_depIdxs = nil
}
